
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '../../types/supabase-db';

const SUPABASE_URL = "https://jocuncymvrkfzrogpezr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvY3VuY3ltdnJrZnpyb2dwZXpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNzU2ODEsImV4cCI6MjA2NDg1MTY4MX0.DcwazGPVfSCTcFMGe5MzJtkPiOnw7MwkLUD6cWGHR5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
